name: generate snake

on:
  schedule: # a cada 12h
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: RuanTrindade
          outputs: dist/snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg
