name: Generate Snake

on:
  schedule: 
    - cron: "0 */12 * * *" # roda a cada 12 horas
  workflow_dispatch: # permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake (SVG + GIF)
        uses: Platane/snk@v3
        with:
          github_user_name: RuanTrindade
          outputs: |
            dist/snake.svg
            dist/snake.gif

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
